### ISSUE TITLE
cant delete 2 folders and files under those folders ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#10]
I cant delete these 2 folders and all folders and files under it tried in filezilla ftp and also cpanel ? 
does the script when install change the group / user I saw 99/99 maybe this is in install ? everything else is able to rename edit and delete ??

**Comment by spirogg** [comment]
![cannot delete these folders and under in cpanel or ftp filezilla](https://user-images.githubusercontent.com/17736688/40588467-1b2dd160-61a3-11e8-83bd-419a7e4af6ea.PNG)

**Comment by spirogg** [comment]
![owner-group](https://user-images.githubusercontent.com/17736688/40588502-bc46ef50-61a3-11e8-9543-6fc7368ea74f.PNG)
![owner-group1](https://user-images.githubusercontent.com/17736688/40588503-bc5420b2-61a3-11e8-934d-727107429ba1.PNG)
![user-group3](https://user-images.githubusercontent.com/17736688/40588504-bc6798f4-61a3-11e8-89f2-7957173a871e.PNG)

**Comment by spirogg** [comment]
I have to delete using ssh only - really weird

**Comment by MacWarrior** [comment]
Hi
This must be related to your server configuration, can't do anything :/
