### ISSUE TITLE
user doesn’t exist

### ISSUE THREAD

**Issue by Erreur1978** [MacWarrior/clipbucket-5.0#102]
I'm on Ubuntu 14.x, php7 with the latest version of clipbucket. Installation all is well .. when I enter my user admin and pass it says to me *user does not exist. even if I create a new user he tells me the same thing.

**Comment by MacWarrior** [comment]
Hi,
I can't reproduce this error but I had some related issues today while testing PHP 7.3
After initial setup or new user creation ; do you still get this error with latest version of the repo ?

**Comment by MacWarrior** [comment]
Hi,
I've been working on this kind of issue today, seems good now with latest version of the repo.
