### ISSUE TITLE
Disable Downloads

### ISSUE THREAD

**Issue by nameuserof** [MacWarrior/clipbucket-5.0#106]
Is there a way to disable downloads?

![2019-08-27 23_21_54](https://user-images.githubusercontent.com/54602650/63809000-87be2500-c921-11e9-903d-84658252d174.png)
![2019-08-27 23_22_11-Full HD Test 1080p - ](https://user-images.githubusercontent.com/54602650/63809001-87be2500-c921-11e9-8726-753b842e40f2.png)

**Comment by MacWarrior** [comment]
Hi,

In admin area : 
Users > User levels > Guest (Primary, but other too) > General Permission : User can download videos

Setting this option to NO should disable the download button ; but anybody could still download the video because the link stay in the HTML
