### ISSUE TITLE
Conversion problem

### ISSUE THREAD

**Issue by nameuserof** [MacWarrior/clipbucket-5.0#109]
Installed with script on 16.04

All videos I upload fail:

![grafik](https://user-images.githubusercontent.com/54602650/64098931-59e54000-cd68-11e9-8492-fd50d14236e6.png)
![grafik](https://user-images.githubusercontent.com/54602650/64098966-6ff30080-cd68-11e9-9112-bbcb33e246de.png)
![grafik](https://user-images.githubusercontent.com/54602650/64098981-76817800-cd68-11e9-9cfc-91fd9c3b0765.png)
![grafik](https://user-images.githubusercontent.com/54602650/64098995-80a37680-cd68-11e9-9516-ceb2b7e28353.png)

**Comment by nameuserof** [comment]
`Converion Log for file .

Reading Conversion log for file
Conversion details
Raw Conversion Log


==========================================
Pre-Check Configurations
==========================================

File to be converted
--------------------
Initializing File 1567410486d7b5f.mp4 and pre checking configurations...

Temporary Uploading
-------------------
File Uploaded to Temp directory successfully and video conversion file is being executed !

Video Conversion File Execution
-------------------------------
Video Converson File executed successfully with Target File > !1567410486d7b5f.mp4


==========================================
Starting Conversion Log
==========================================

Getting Arguments
-----------------
Filename : 1567410486d7b5f.mp4
File directory : 2019/09/02
Log file : /home/http/clipbucket/upload/files/logs/2019/09/02/1567410486d7b5f.log


Conversion queue
----------------
Getting the file information from the queue for conversion

Conversion queue
----------------
File has been moved from temporary dir to Conversion Queue

Parsing FFmpeg Configurations
-----------------------------
use_video_rate : 1
use_video_bit_rate : 1
use_audio_rate : 1
use_audio_bit_rate : 1
use_audio_codec : 1
use_video_codec : 1
format : mp4
video_codec : libx264
audio_codec : libfdk_aac
audio_rate : 22050
audio_bitrate : 128000
video_rate : 25
video_bitrate : 300000
video_bitrate_hd : 4096000
normal_res : 480
high_res : 720
max_video_duration : 320
resize : max
outputPath : 2019/09/02/
cb_combo_res : no
gen_240 : yes
gen_360 : yes
gen_480 : yes
gen_720 : no
gen_1080 : no
chromecast_fix : 1


Starting Conversion
-------------------
Started on 2019-09-02 09:48:11 - 2019 Sep 02

Checking File...
File : /home/http/clipbucket/upload/files/conversion_queue/1567410486d7b5f.mp4

File Exists
-----------
Yes

Preparing file...
-----------------
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 22.34
size : 9090405
bitrate : 3255878
video_width : 640
video_height : 480
video_wh_ratio : 1.3333333333333
video_codec : h264
video_rate : 29.97
video_bitrate : 3093910
video_color : N/A
audio_codec : aac
audio_bitrate : 160504
audio_rate : 48000
audio_channels : 2
path : /home/http/clipbucket/upload/files/conversion_queue/1567410486d7b5f.mp4
rotation : 0


Thumbs Generation
-----------------
Starting

Thumbs Files
------------

====== End : Thumbs Generation =======


Conversion Ouput
----------------


=======Low Resolution Conversion=======


Sarting : Generating Low resolution video @ 2019-09-02 09:48:16

Converting Video SD File

Command : /usr/bin/ffmpeg -i /home/http/clipbucket/upload/files/conversion_queue/1567410486d7b5f.mp4 -vcodec libx264 -acodec aac -ac 2 -s 640x480 -preset medium -f mp4 -vb 300000 -ab 128000 -r 25 -ar 22050 /home/http/clipbucket/upload/files/videos/2019/09/02/1567410486d7b5f-sd.mp4

Sarting : MP4Box Conversion for SD

MP4Box Command : /usr/bin/MP4Box -inter 0.5 /home/http/clipbucket/upload/files/videos/2019/09/02/1567410486d7b5f-sd.mp4 -tmp /home/http/clipbucket/upload/files/temp

Conversion Status : Successful @ 2019-09-02 09:48:17


OutPut Details
--------------
format :
duration : 0
size : 0
bitrate : 0
video_width : 0
video_height : 0
video_wh_ratio : N/A
video_codec :
video_rate :
video_bitrate : 0
video_color : N/A
audio_codec :
audio_bitrate : 0
audio_rate : 0
audio_channels : 0
path : /home/http/clipbucket/upload/files/videos/2019/09/02/1567410486d7b5f-sd.mp4
rotation : 0


Conversion Completed
--------------------

====== End : Thumbs Generation =======


Time Took : 5.6828 seconds

conversion_status : failed
`

**Comment by pnemuk** [comment]
check if libfdk is installed on ffmpeg.

**Comment by nameuserof** [comment]
how do I check this?

**Comment by pnemuk** [comment]
type in your server console
ffmpeg -v

**Comment by nameuserof** [comment]
nevermind, I just reinstalled on 18.04 and it worked flawlessly
