### ISSUE TITLE
Deprecated functions.

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-5.0#114]
There are 2 functions in session.class.php that have been deprecated in PHP 7.3.

session_register()
session_unregister()

**Comment by MacWarrior** [comment]
Hi,

Thanks for report, will check this asap

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi,

Function has been removed in this commit : 761e914fd6ab1fb2bb140a8f5ff37aa74831db88

Best regards,
MacWarrior.
