### ISSUE TITLE
Stay MP4 as it is box

### ISSUE THREAD

**Issue by Rockyuk** [MacWarrior/clipbucket-5.0#115]
Hello Everyone,
I am trying to use the Stay MP4 as it is box but everytime i press it and try to save it it does not work. Can i activate this in the conifguration file to over ride this issue?

ClipBucket V5.2.0 STABLE

Thanks

Rockyuk

**Comment by MacWarrior** [comment]
Hi,

This looks like a DB missing config issue, you might need to init this specific config manually, will check this asap

Best regards,
MacWarrior.

**Comment by Rockyuk** [comment]
Ahhh, that would make sense is there a DB command I can run to add it or manually add it to the DB?

**Comment by MacWarrior** [comment]
Hi,

This config was missing from SQL files (fixed in last commit)

You can execute this command to create the missing config (don't forget to edit {tbl_prefix} with your personnal DB prefix) :
```INSERT INTO `{tbl_prefix}config`(`name`, `value`) VALUES
	('stay_mp4', 'no');```

Best regards,
MacWarrior.
