### ISSUE TITLE
Large Video Uploads

### ISSUE THREAD

**Issue by Rockyuk** [MacWarrior/clipbucket-5.0#117]
Hi there,
I have been uploading large files upto 1 Gig perfectly fine. Today I tried a 4 gig video and it uploaded at 100% and gets stuck. I also noticed that it cycled through the progress bar twice everytime and then stalls on 100%, can't press submit or do anything. I also have the stay the same MP4 button ticked as well. All video uploads are MP4.

Clipbucket 5.2.0 Stable

Thanks

Rockyuk

**Comment by MacWarrior** [comment]
Hi,

Can you check Admin > Tool Box > Server Configuration info : 
- Post Max Size must be > 4G
- Upload Max Filesize > 4G
- Max Execution Time > The time you used to upload your file

Thanks

**Comment by MacWarrior** [comment]
Hi, 

Please re-open this ticket if you still have this issue

Best regards,
MacWarrior.
