### ISSUE TITLE
I want to Authenticate my users Through LDAP

### ISSUE THREAD

**Issue by aktiwari4u** [MacWarrior/clipbucket-5.0#118]
Hi All,
I want to authenticate my users through LDAP. Is there any open source plugin  for ldap authentication with current version.

**Comment by MacWarrior** [comment]
Hi, 

This seems to be integrated in the official entreprise paid version (3799£ :sweat_smile:)
With a quick google search, I couldn't find any LDAP free plugin (A plugin compatible with latest official free version should be fully compatible with "my" version)

The only thing I can do for now is to wish you good luck finding some free plugins :wink:

Best regards,
MacWarrior.
