### ISSUE TITLE
when upload multiple photos - the image gets bigger in lower right corner see photos

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#12]
![upload more photos 1](https://user-images.githubusercontent.com/17736688/40589598-91960a0e-61b5-11e8-97b2-d5361b553117.PNG)
![upload more photos 2](https://user-images.githubusercontent.com/17736688/40589599-91a547da-61b5-11e8-94ea-bda896064381.PNG)
![upload more photos too big](https://user-images.githubusercontent.com/17736688/40589600-91b155ca-61b5-11e8-9ced-1ae0fb1bd51b.PNG)
![upload more photos](https://user-images.githubusercontent.com/17736688/40589601-91c3250c-61b5-11e8-80df-30161c4d6b79.PNG)
![upload more photos3](https://user-images.githubusercontent.com/17736688/40589602-91d91f1a-61b5-11e8-9cab-91e868d0e065.PNG)

**Comment by MacWarrior** [comment]
Hi, 

Fixed in this commit : 5ceccd9aab8cc1988b8d2919f5b37eae93968df3
