### ISSUE TITLE
settings area>> user listing>> subscribers in channel view not saving after set a number ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#13]
hi see photo this will not allow me to save a number ?

-

![subscribers in channel view](https://user-images.githubusercontent.com/17736688/40589681-70f069f0-61b7-11e8-8c09-de6141b4ec84.PNG)

**Comment by MacWarrior** [comment]
Hi
I'm not sure this is ment to be edited, will check

**Comment by MacWarrior** [comment]
Hi,
This option wasn't used anywhere ; I deleted it : 1021cb0838595abc1c13a6a6f353c7e62ed3f64a
Don't forget to apply SQL
