### ISSUE TITLE
when upload png file in photos image in lower corner not show

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#14]
when you upload a photo png the photo doesnt show in upload form - lower right corner
![added to new collection](https://user-images.githubusercontent.com/17736688/40589902-64225914-61bb-11e8-88dd-fb3ea9b36ff2.PNG)

**Comment by spirogg** [comment]
Seems only jpg files show ?

**Comment by MacWarrior** [comment]
Hi,
Did you allowed PNG format in General Configurations > Website Configurations ?
![capture](https://user-images.githubusercontent.com/200590/40627670-9391f5a0-62c0-11e8-82e8-72a6b2de6443.PNG)

**Comment by spirogg** [comment]
yes its there

- I can upload png 

- but only the png doesnt show in that area

**Comment by MacWarrior** [comment]
Thanks ; will try

**Comment by MacWarrior** [comment]
Hi,
Photo is well uploaded, but the display is forced to .jpg (So it won't never work with orther files than .jpg file this way...)

Working on it

**Comment by MacWarrior** [comment]
Please update to this commit : 0a3b588dcc930c92640f5d6a35eb30722b87057e
