### ISSUE TITLE
signup button not show using android phone ? 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#16]
- when using mobile android phone the signup button doesn't show 

-

![screenshot_20180527-145237](https://user-images.githubusercontent.com/17736688/40590055-16d13bfa-61be-11e8-9e64-8514474caa5f.png)

**Comment by spirogg** [comment]
@MacWarrior

Is there a way to get a quick fix for this one. - Sign up button ? 
or what file to look in to try and figure it out. 

Thanks 

Spiro.

**Comment by MacWarrior** [comment]
Hi,

I made a mistake, this is clearly a bug : fixed in last commit
