### ISSUE TITLE
comment then respond says reponde 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#18]
hi where can I fix the english to respond in comments (when you respond to a commnet) also in respond field make to english ?

thanks
![where i can change this respond](https://user-images.githubusercontent.com/17736688/40591119-a9aef5ea-61d0-11e8-9d78-bfa894da45f4.PNG)

**Comment by MacWarrior** [comment]
Seems like I made some hardcoded french translations...
Will check soon

**Comment by MacWarrior** [comment]
Note : Therse are managed directly in JS file
There is no proper way to translate it, but I'll try

**Comment by MacWarrior** [comment]
Hi,
Please update to this commit : 9e3f485e6c7594b6543db6a1b5625332c44af2fc
