### ISSUE TITLE
in the the video player it says par admin top right corner where can i change to remove par

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#19]
hi in the player it says par admin where can we remove the par and make it By admin or by user ?

thanks so much for this player it works awesome !!! really does 
you made it really nice 💯 🥇

**Comment by MacWarrior** [comment]
Hi,
This is the same problem as #18, hardcoded text in JS file
Will work on it

**Comment by MacWarrior** [comment]
Hi, 
Please update to this commit : 89759003bde2bfa70f3db2219446d9fff9d3bc6b
