### ISSUE TITLE
i found old plugin for audio ver 1.5 ? for CB can you use it ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#20]
do you have audio plugin for cb or can you use old one and redo for audio also ? 
I found in my files at home from ver 2.6 CB my old plugin if you are interested. 
cb_audio plugin I can upload here for you. I try it doesnt install :(

thanks

**Comment by spirogg** [comment]
[cb_audio_1.5.zip](https://github.com/MacWarrior/clipbucket-5.0/files/2043144/cb_audio_1.5.zip)

**Comment by MacWarrior** [comment]
Hi
It is a free or premium plugin ?

**Comment by spirogg** [comment]
I don't remember to be honest. . It was long time ago. Maybe was free ??
Back then.

**Comment by spirogg** [comment]
just let me know I can link it and after I can delete link ?

**Comment by spirogg** [comment]
if you see code you can tell if premium or free ?? it was from 2011 i think

**Comment by MacWarrior** [comment]
I can't put it online if it's a premium module, you have to make sure that it was free

**Comment by spirogg** [comment]
ok 

- I don't remember if I purchase or got it free from friends in forum or they allowed us to download it. 
- I was just purging my hard drive from old cb files and other stuff and found it :(
- I will email CB myself and ask them if it was that old and was free ?
- I will post here after make 100% sure its free and ok to work on :)
