### ISSUE TITLE
user michelle has wrong profile photo when viewing her photo

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#21]
see photos, when viewing a users photos the profile for that user shows admins profile photo

when viewing a users videos it is working correctly

see photos below

-this is when viewing photos 
-
![user michelle has my profile photo](https://user-images.githubusercontent.com/17736688/40592463-4df671d2-61e5-11e8-81d6-eed514b712b4.PNG)

-this is when viewing videos its correct 
-
![in videos michelle has correct profile photo](https://user-images.githubusercontent.com/17736688/40592481-8098943a-61e5-11e8-8aa8-6d08f8840ae9.PNG)

**Comment by spirogg** [comment]
![user profile wrong](https://user-images.githubusercontent.com/17736688/40592768-9467d144-61e8-11e8-9cd4-e4650f50d5cc.PNG)

**Comment by spirogg** [comment]
whom ever is logged in that is the profile picture you will see when viewing a photo
![whom ever is logged in will show thier profile picture when viewing photos](https://user-images.githubusercontent.com/17736688/40603048-637a2e6e-6220-11e8-8164-e7419b82e51e.PNG)

**Comment by spirogg** [comment]
- also when logged out no profile picture shows in photo section

-

![no profile pics show when lkogged out only in photo section](https://user-images.githubusercontent.com/17736688/40604448-a8b4e952-6224-11e8-9317-1c64a6d93ce1.PNG)

-
- but in video section it shows when logged out

-
![profile pic only in videos when logged out](https://user-images.githubusercontent.com/17736688/40604486-cde6f184-6224-11e8-80fe-8a001a3b5dc4.PNG)

**Comment by MacWarrior** [comment]
Weird bug... will try it

**Comment by spirogg** [comment]
Maybe because using base URL instead of complete link to profile and user is logged in it takes user's profile photo while slogged in ??

**Comment by MacWarrior** [comment]
Hi,
I've made lots of fixes since this issue was oppened, this is fixed now, I just don't remember when I did it
