### ISSUE TITLE
hi I also notice in chrome browser I right click and inspect viewing console the date is not correct ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#23]
hi I also notice in chrome browser I right click and inspect viewing console the date is not correct ?
see photo
- is this normal ? or is script setting wrong date
instead of get date and time from realtime - or server date and time ?

-
![date is not correct in user activity chrome console i see this](https://user-images.githubusercontent.com/17736688/40597279-1703279e-6206-11e8-91cb-60f1a2dac2f3.PNG)

-
![user activity time is not correct in console says 2016-03-31](https://user-images.githubusercontent.com/17736688/40597284-1f00b984-6206-11e8-9816-2ff3b2934ee2.PNG)
-
-
-Clipbucket script latest version from github same issue with date ?
-

![cb-script same thing](https://user-images.githubusercontent.com/17736688/40598015-d254c31e-620a-11e8-8087-03848d518aa3.PNG)

**Comment by spirogg** [comment]
not sure if this is an iassue or not just posting so you are aware :)

**Comment by MacWarrior** [comment]
Functionnally, there is no impact because this date seems to not be used
But is this date related to SEO ? Or social sharing ?

**Comment by MacWarrior** [comment]
Hi, 
This may be fixed by this commit : 334426c6921f206cd2d04ba0144809d46d6e1bfa
