### ISSUE TITLE
language editor seems weird see photo

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#24]
hi it seems that some wording in language editor is out of the field form ? really weird is there a way to fix this or too much work ?

![language editor seems weird](https://user-images.githubusercontent.com/17736688/40601693-c6b714a6-621b-11e8-8397-97f5f8e41352.PNG)

**Comment by spirogg** [comment]
same on CB i close this one

**Comment by MacWarrior** [comment]
Don't close even if reproduced on "basic" CB, I will fix it to :)
(Btw, most of bugs you'll find will be on the "basic" too)

**Comment by MacWarrior** [comment]
Hi, 
Please update to this commit : 0269143a157edf7b10262bc1d9fb3ab6bab9b946
Texts were not secured on display (This is the result of a XSS injection, and this could be worse)
