### ISSUE TITLE
just a question 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#25]
is this you France

9:47 AM
Monday, May 28, 2018 (GMT+2)
Time in Paris, France

**Comment by MacWarrior** [comment]
Hi,
It could be but I'm at work and didn't do anything at this time
Where did you get this log ?

**Comment by spirogg** [comment]
no log
 I saw your words were french ( édité par MacWarrior) 
(Par admin) in video player top right
also when reply to comment in CB (Répondre à admin...)

so I assume you were in France :) I am in USA but Originally from Greece 
sorry to bug ya at work ill leave you alone

**Comment by MacWarrior** [comment]
Hardcoded translations will be fixed as soon as possible ;)
