### ISSUE TITLE
When subscribe to a user can we change button to say unsubscribe ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#28]
- Hi would it be really hard to make subscribe button say unsubscribeadter a user has subscribed to a user. 
- Also if a user wants to unsubscribe they can click unsubscribe. And it goes back to subscribe. ? 

- Or change to follow and unfollow. ? 

Thanks

**Comment by spirogg** [comment]
![subscribe](https://user-images.githubusercontent.com/17736688/40624353-b4af1a14-6271-11e8-8f96-57a6efffd2d0.PNG)
-

![subscribe2](https://user-images.githubusercontent.com/17736688/40624354-b4bd9b48-6271-11e8-9583-868d3d27cf24.PNG)
-

![subscribe3](https://user-images.githubusercontent.com/17736688/40624355-b4caa176-6271-11e8-88b7-a8bd459c75d1.PNG)

**Comment by MacWarrior** [comment]
Hi, 

Please see last commit for this enhancement and some fix related
