### ISSUE TITLE
how to add chromecast to latest version of CB is it easy ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#3]
hi I see you added chromecast for your 5.1 CB 

but I uploaded yours and there is lots of working with Sign_up_now underscores etc in language file. 

would it be easy to copy over files to get it to work ? or will it ruin my install ?

thanks

Spiro

**Comment by MacWarrior** [comment]
Hi

I've made lots of modifications since a long time for this, I think it would ruin your clipbucket "basic" install and it is related to video conversion, so you may have to reconvert your videos
I know for the translation problem on fresh install, still working on it

**Comment by spirogg** [comment]
I have a program phpmelody I am wondering is there a way we can bridge this to clipbucket ? the admin area of phpmelody.com go check the admin area how you can search for youtube and other videos sites and with a click of a few buttons there all imported and it has cron to tell you if the youtube videos is off line, user cancel video from view, etc.. also it has a save search where it will add new videos automatically  every day 3 day or 5 days to your website.  i wish we can have this importer for use in CB.

if you need to see this with code and everything i can make it happen I already buy this script but not have ffmpeg upload :( just upload but user has to add photo so I dont like it to much front end - https://demo.phpmelody.com/

but for embed videos the back end - https://demo.phpmelody.com/admin/login.php
 it is awesome

**Comment by spirogg** [comment]
![phpmelody importer](https://user-images.githubusercontent.com/17736688/40574387-46204258-6096-11e8-8cf5-5895044a3a11.PNG)
![phpmelody search function](https://user-images.githubusercontent.com/17736688/40574388-4ac1c1e2-6096-11e8-8d81-1fed21ecd5ee.PNG)

**Comment by MacWarrior** [comment]
Hi, 

I'm not currently working on this kind of feature ; plus this would requiere lots of implementation
Maybe this can be done more easily by intregating an external service specialized in this but it would add a dependance to this external service

**Comment by MacWarrior** [comment]
I've fixed the translation problem ; please update to this commis : 
https://github.com/MacWarrior/clipbucket-5.0/commit/0dbe8feb06ee71ccb965e56f601bcf06f829d690

**Comment by spirogg** [comment]
K thanks.
