### ISSUE TITLE
Chromecast support limit audio to stereo

### ISSUE THREAD

**Issue by MacWarrior** [MacWarrior/clipbucket-5.0#30]
Currently, to allow the Chromecast support, I've had to limit audio quality to stereo (2 channels)
This is requiered because Chromecast (2 and ultra) drops the support for AAC with more than 2 channels
Cf. https://productforums.google.com/forum/#!topic/chromecast/zPl3sDIyttk

I'm currently trying multiples cases to allow : 
- Chromecast with multi-channel
- Desktop browsers (Chrome, Firefox, Opera and if possible IE)
- Mobile browsers (Chrome, Safari)

Cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by spirogg** [comment]
Noticed the same thing as everyone else -- AAC not working. It's a pain to go through all your AAC media but it can be easily converted to AC3:

ffmpeg -i inputvideowithaacaudio.mp4 -c:v copy -c:a ac3  outputvideowithac3audio.mp4

**Comment by MacWarrior** [comment]
Just check the links, it's the first one ;)

Already tried AC3, not working well...
Will post my tests results tonight

**Comment by MacWarrior** [comment]
Hi, 

Option added in this commit : 74326422cf496247b07cc839f75a570490db5615
A SQL is to apply : /cb_install/sql/upgrade_5.1.sql
