### ISSUE TITLE
When uploading from my mobile .3gp if set all 240,360,480 not working 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#31]
Hi I if I set my setting in admin to 240, 360 or 240, 360, 480 etc. When I try to upload from my phone it's .3gp format. It doesn't work. If I set it to SD HD it works. 
I use to have in older ffmpeg.class.php an area that said threshold I use to set to 100 or 50 and if I can remember correctly it use to work when set to all 240, 360 etc. 
- but If I take video first. Then upload from my phone /video/folder  the video is uploaded as .mp4 and it works. ?? 

- I see you changed threshold. Should I add 50 in front of your code: 240, 360, 480, etc. Will this work ? 
- I'm assuming the file in .3gp is smaller than 240 so it won't convert ? 

- your thoughts or ideas ?

**Comment by MacWarrior** [comment]
Hi,
What is your original .3gp video resolution ?

Per example, if it's 720x1280, it will be converted in : 240p, 360p, 480p and 720p but not in 1080p beause the source file is limited to 720p

**Comment by spirogg** [comment]
I fixed this. My camera app from ZTE is only recording 176x??? So too small. Fir some reason. But when I record video first then upload from file folder works awesome. 

So I just download from app store different camera app that has mp4 output and works fine. 
No worries. We can close this one. 

Thanks.
