### ISSUE TITLE
I add a different file .m2t for test upload of video and when delete 6 videos lost all thumbs. 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#32]
Hi I wented to test some different video types. So I add them in configuration. I tried each one all worked except for .m2t (can't remember exactly the name but I think that was it )  but it failed. 
 - So when I went into admin to manage videos and clicked drop-down to delete that video, It cleared out 5 or 6 different  videos - all there thumbs we're gone. I can recreate them but was this error ? Is this fault of script. A bug. Why would when you delete a video wipe other video thumbs. ?

Thanks. :)

**Comment by spirogg** [comment]
It's happened before also when a video fails. Even .3gp video failed it wiped out previous thumbs.

**Comment by spirogg** [comment]
https://github.com/arslancb/clipbucket/issues/108

**Comment by MacWarrior** [comment]
Jut tried to delete therse : 
![capture](https://user-images.githubusercontent.com/200590/40807997-1f4d5550-6526-11e8-8111-a7a561826540.PNG)

No problem deleting one by one with the dropdown menu (which is linked to video ID)
I only use mass upload ; did you upload from FO upload interfaces ?

There's also a bug on video thumbnails generation : after a certain number, it start over ; it's not critical, just generating from the beginning of the video (On 50 thumbnails generation, the last ~5 are in this case)

Day is over here in the Parisian suburb ; have a nice day too !

**Comment by spirogg** [comment]
Hi I upload 1 by one using reg upload. Not mass upload. Maybe that's the difference.

**Comment by spirogg** [comment]
Happened inlynwhen I upload a few videos and then I upload one video that fails. If video fail then ingo to delete the failed video tyen it happens. Not always but did happen a few times.

**Comment by spirogg** [comment]
Try to upload a few videos. Then make one video fail. Then after it fail go to admin area find it click drop down then delete  Then also try to upload again another couple videos and makenin fail  then go to admin area and find video click drop-down to edit and in edit video in admin see if you can delete and see if it happens there. I will test again when I get home later tonight and see if I can reproduce also. 

Thanks.

**Comment by spirogg** [comment]
I've reporduced it again. While uploading videos one by one and still some converting I uploaded the .m2t video format that won't convert. Then I go to edit the .m2t video and see it has no conversion log. Says it has 100 thumbs and it has a copy of all the videos I just uploaded - their thumbs when I go to edit video in admin area. When I delete it. It deleted the thumbs of the other videos.  Will try to link the actual video so you can upload it and try it yourself shortly with some snapshots of what happens.

**Comment by spirogg** [comment]
![4 new conversions good](https://user-images.githubusercontent.com/17736688/40870147-9dfcc0d4-65ee-11e8-81f8-2bb4e5c60142.PNG)
![5 videos missing thumbs](https://user-images.githubusercontent.com/17736688/40870148-9e0b897a-65ee-11e8-8b4d-d3dd8866555e.PNG)
![edit video 1](https://user-images.githubusercontent.com/17736688/40870149-9e182bbc-65ee-11e8-88d7-caae3a80ad53.PNG)
![edit video 2](https://user-images.githubusercontent.com/17736688/40870150-9e276910-65ee-11e8-94e2-4637001c4cc3.PNG)
![edit video](https://user-images.githubusercontent.com/17736688/40870151-9e331292-65ee-11e8-9b58-7d32b75f19e8.PNG)
![no thimbs after delete bad video](https://user-images.githubusercontent.com/17736688/40870152-9e45b028-65ee-11e8-95a1-8d208898887f.PNG)
![videos - 1 is not good](https://user-images.githubusercontent.com/17736688/40870153-9e527ad8-65ee-11e8-8393-e6bc83b6da2b.PNG)

**Comment by spirogg** [comment]
- the last photo shows still processing and took thumb from either 1005 or 1007 video
- but in edit video it shows all thumbs from all 4 videos

**Comment by spirogg** [comment]
here it happens again even after all 6 videos have been converted. then upload m2t video format then it removes again all 6 thumbs

![m2t video format](https://user-images.githubusercontent.com/17736688/40870235-d66defea-65f0-11e8-9ef1-63a8a16ac135.PNG)
![removed 6 thumbs](https://user-images.githubusercontent.com/17736688/40870236-d953932c-65f0-11e8-8442-48753c3f6942.PNG)

**Comment by spirogg** [comment]
https://www.hdpvrcapture.com/wordpress/?page_id=97

**Comment by spirogg** [comment]
http://standaloneinstaller.com/blog/big-list-of-sample-videos-for-testers-124.html

ok I tried all these formats
- all works
except for .mts file format  when upload mts file format after adding to configuration  then the thumbs get deleted to all videos i recenlty uploaded  even if you have 2 videos mp4 uploaded then you upload mts file format you get error all thumbs show as in photos and when you delete mts file format it deletes all other thumbs of recent uploaded videos, so it cannot convert so it creates this error. so we just not add that format to config and it wont allow to upload and ruin other thumbs. :)

**Comment by spirogg** [comment]
- so far I have tried these and they working so far so good
mkv,m4v,wmv,avi,3gp,mov,mpeg,mpg,xvid,flv,mp4
- i have not tried these yet
divx,xvid,asf,rm,dat

**Comment by spirogg** [comment]
- so really not a bug maybe ffmpeg not convert these file formats = m2t, m2ts, mts
so it creates the thumbs issue ? no big deal I guess
- one Question : why when convert video to 3 formats 240,360,480  i see it says 25 thumbs for each of those videos ? when I have 5 thumbs selected ? 
- one Suggestion, we have in video manager option to select and delete feature un-feature and reconvert
 - maybe we can make option also to select : and regenerate thumbs for multiple videos if ever this happens, and make regenerate 1 video at a time - or option like reindex
Loop Size
number of video thumbs to regenerate at once 
>>>>       2      <<<



something like the reindex area so not do all at once? 
Re-index Clipbucket 
Here you can re-index your videos, users or groups statistics. From below select which thing you want to re-index.

Loop Size
number of items to reindex at once 
>>>>       5      <<<
Reindex Videos
Reindex Users
Reindex Groups
Reindex Collections
Reindex Photos
Reindex Videos

this will reindex total playlists, total favorites and total comments made on video
Indexing 11 - 13 of 13
71: Updating jhgjhg
76: Updating Minecraft-Wallpaper-1
82: Updating noah and fia
Indexing has been completed.

**Comment by MacWarrior** [comment]
Hi,
I generated failed conversion while testing OPUS audio codec but it didn't reproce when I deleted videos
Can you update an example of .m2t file ?

Thumbails are generated in independently of the convertion sizes

**Comment by spirogg** [comment]
Hi sorry I fell asleep. Was so tired. Now I'm awake. Here is the link. https://cinelerra-cv.org/footage.php

And here is the actual video .m2t

https://cinelerra-cv.org/footage/surfing-PP1-on-then-off.m2t

**Comment by spirogg** [comment]
same thing after update.

![thumbs](https://user-images.githubusercontent.com/17736688/40890494-903cbec8-673c-11e8-82d5-323cdf668f2b.PNG)
![thumbs1](https://user-images.githubusercontent.com/17736688/40890495-93e27f7c-673c-11e8-8711-09942e4f5351.PNG)
![video stuck in processing no log](https://user-images.githubusercontent.com/17736688/40890496-98199864-673c-11e8-8734-f59adb736c4b.PNG)
![samething](https://user-images.githubusercontent.com/17736688/40890500-a7b8bed0-673c-11e8-8e10-5edf268328d4.PNG)

**Comment by spirogg** [comment]
really weird

**Comment by MacWarrior** [comment]
Hum... This is akward...
![capture](https://user-images.githubusercontent.com/200590/40891262-a8240140-6782-11e8-8665-c449c751c5cd.PNG)

This must be related to the server configuration, or ffmpeg version, maybe ?

**Comment by spirogg** [comment]
yes ffmpeg version I'm thinking same thing 

```
ffmpeg version N-91152-g7c333dc6a7 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
  configuration: --prefix=/usr/local/ffmpegtoolkit --pkg-config-flags=--static --extra-libs=-lpthread --enable-gpl --enable-shared --enable-nonfree --enable-pthreads --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --enable-libvpx --enable-libfdk-aac --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-postproc --enable-swscale --enable-avfilter --enable-libass --enable-runtime-cpudetect --extra-cflags=-I/usr/local/ffmpegtoolkit/include/ --extra-ldflags=-L/usr/local/ffmpegtoolkit/lib --enable-version3
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 19.102 / 58. 19.102
  libavformat    58. 16.100 / 58. 16.100
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 24.100 /  7. 24.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

**Comment by spirogg** [comment]
I need for another script 3.0 and higher - if I use centos 7 ffmpeg from yum it is only 2.8 So I install this other one

https://github.com/hostsoft/ffmpegtoolkit

**Comment by MacWarrior** [comment]
```
ffmpeg version 3.2.10-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
```

**Comment by spirogg** [comment]
hmmm ?? how to make install of yours now can i change this ? with proper stuff ?

**Comment by MacWarrior** [comment]
This is the version I got on a clean Cent OS 7 installation : 
```
ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-4)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfaac --enable-nonfree --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
```

So there is a real difference between Debian and Cent OS 7 repositories ; I will test .m2t video import on that plateform to check, but you definitely don't have the same version, maybe this is related with your ffmpeg installation script

**Comment by spirogg** [comment]
Yes please test with ffmpeg version 2.6.8
If not issues then my ffmpeg is the issue.

**Comment by spirogg** [comment]
I am just not really good with command line for making server configuration and websites etc etc. That's why I use cPanel. :(

**Comment by spirogg** [comment]
i found and installed this version, now i will test

```
ffmpeg version n3.2.10 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
  configuration: --prefix=/usr/local/ffmpegtoolkit --pkg-config-flags=--static --extra-libs=-lpthread --enable-gpl --enable-shared --enable-nonfree --enable-pthreads --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --enable-libvpx --enable-libfdk-aac --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-postproc --enable-swscale --enable-avfilter --enable-libass --enable-runtime-cpudetect --extra-cflags=-I/usr/local/ffmpegtoolkit/include/ --extra-ldflags=-L/usr/local/ffmpegtoolkit/lib --enable-version3
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
server1:~#
```

**Comment by spirogg** [comment]
Still same.isie for.me. But in another video script. Phpvibe.com. I upload the video I gave you link too  same video surf mt2 and it works. No problem.

**Comment by MacWarrior** [comment]
So if I understand : 

This one is working : https://cinelerra-cv.org/footage/surfing-PP1-on-then-off.m2t
But another isn't ? Can you link it ?

**Comment by spirogg** [comment]
Hi. Yes that one works on another script. Phpvibe.com. But not on CB

**Comment by spirogg** [comment]
I reinstalled ffmpeg I tried a few different versions. They all worked  on
another script. phpvibe.com. with that file. But clipbucket never worked
for me. On any of these versions of ffmpeg. Keeps doing the same thing.
Takes thums from all recent and when I delete .m2t file. It deleted thumbs
from other videos. ?? Really weird.

**Comment by spirogg** [comment]
What's weird is I don't even get log file. To check what's wrong. Where can I see error for that video after try upload. Anywhere I can see on server ??

**Comment by spirogg** [comment]
Quick question ?
- Do you have plugin thumbs activated in your CB ? 
- could it be permissions of some folder - file ?

**Comment by MacWarrior** [comment]
1) No plugins, basic install
2) Try chmod 777 -R on the installation directory, you'll see (But I don't think this is it)

**Comment by spirogg** [comment]
What versions do you have. 
Also I ls MP4Box 0.7.1 too old ?? Is there newer version and can I just update this ??

![img_20180604_144544](https://user-images.githubusercontent.com/17736688/40938007-1d0b9cf6-6806-11e8-9d22-e535ef87a855.jpg)

**Comment by MacWarrior** [comment]
FFMPEG : 3.2.1
PHP CLI : 7.0.2
Media info : 0.7.91
MP4Box : 0.5.2
ImageMagick : 6.9.7
FFProbe : 3.2.10

Did you checked your php error files ? (Apache AND cli) ?

**Comment by spirogg** [comment]
what about ea4 apache mods ? or php mods what are needed for CB  ?

**Comment by spirogg** [comment]
i looked for logs cant find anything with uploads

**Comment by spirogg** [comment]
aggrevating, all formats work except for .m2t .m2ts
