### ISSUE TITLE
there is a letter T showing when you click in admin area Mass upload videos

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#34]
see photo
![mass upload mystery letter t](https://user-images.githubusercontent.com/17736688/40871545-32234f12-6603-11e8-9110-d1787c4c4eea.PNG)

**Comment by MacWarrior** [comment]
Hi,
I can't reproduce, did you make some code modifications ?

**Comment by spirogg** [comment]
No nothing.

**Comment by spirogg** [comment]
This also happens when regenerate thumbs there is a T top left. See #33

**Comment by MacWarrior** [comment]
I've been looking for that T but I didn't find anything.
Can you try updating your files and check if it disappear ?

**Comment by spirogg** [comment]
I think I know where it came from. Languages. I tried making some changes
to words in languages and saved them  that is what you said you fixed  so I
think that might be it. I need to update files. Will do and let u know. I'm
still working. Will be home in a 3 hours. 9 am. :) Thanks and sorry. :(

**Comment by spirogg** [comment]
ok was fixed when upload files - I think it was the bug in language files, #24
