### ISSUE TITLE
maybe an enhancement for regenerate and select thumb change ? in this area it does it only

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#36]
hi i go to edit video and regenerate thumbs, then select to change thumb for main photo for video
 - after select and then click update thumb, it says updated thumb 
but still not show check mark on selected thumb.
- but when refresh page it is correct - it did change thumb and is selected. 

just fyi - not an issue but maybe enhancement, because I had to refresh to see that it did change, so I was little confused, until refresh and showed correctly :)

see photos

![will save this thumb](https://user-images.githubusercontent.com/17736688/40890734-364c7094-6740-11e8-8c70-e8f35e71c73a.PNG)
![will save this thumb 2](https://user-images.githubusercontent.com/17736688/40890736-39c9e5b2-6740-11e8-95d2-ef6e914af0e9.PNG)

**Comment by MacWarrior** [comment]
Hi, 
I've already noticed this and will work on it

**Comment by MacWarrior** [comment]
Hi, 

Fixed in this commit : 05b0f0192f57c5e5972244428aa46b903b0f6f12
