### ISSUE TITLE
Emails sent don't show correct html format when received. 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#39]
Hi when I get emails from cb when comment or reply or upload video photo. The html is not correct. This is an enhancement. Since we can change - I can work on this if it's just in the email templates. 
- I will test a few and it works out nice I will update them and upload the files here. 

Thanks. 

Spiro.

**Comment by MacWarrior** [comment]
Hi, 
Can you give an example ? (Screenshot or copy/paste)

Thx

**Comment by spirogg** [comment]
Hello Michelle<br /> <br /> You have been notified by mysitename that admin has uploaded new video <br /> <br /> Video Title : jellyfish-25-mbps-hd-hevc<br /> Video Description : jellyfish-25-mbps-hd-hevc<br /> <br /> <br /> <a href="https://t.com/watch_video.php?v=KSYSHHO8MUH2"><br /> <img src="https://t.com/files/thumbs/2018/06/03/152806655182a5a-168x105-1.jpg" border="0" height="90" width="120"><br><br /> click here to watch this video</a><br /> <br /> <br /> You are notified because you are subscribed to admin, you can manage your subscriptions by going to your account and click on manage subscriptions.<br /> mysite name.

**Comment by spirogg** [comment]
That's how it looks in Gmail.

**Comment by MacWarrior** [comment]
Hi, 
Please see this commit : e4e7630400881d7afb7ce03f5525bbe5281a9b52
