### ISSUE TITLE
error imagick

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#4]
error i open development debug i see =
Fatal error: Class 'Imagick' not found in /home/tvz/public_html/includes/functions.php on line 3533

in configuration i have set :
Imagick Path (Not used anymore, will be deleted soon)
/usr/bin/convert I try /usr/local/bin/convert also

my other site have /usr/bin/convert no issues

sorry I thought i was on your repo when I created bug.. 

maybe I can comment out those lines ? in function?

**Comment by MacWarrior** [comment]
Please see my last answer on original issue, this should fix your problem

**Comment by spirogg** [comment]
```
server1:~# yum install -y php-pear
Loaded plugins: universal-hooks
No package php-pear available.
Error: Nothing to do
server1:~#
```

**Comment by spirogg** [comment]
/opt/cpanel/ea-php56/root/usr/bin/pecl install imagick
/opt/cpanel/ea-php70/root/usr/bin/pecl install imagick

working now I found on cpanel thanks sorry for all the headaches Im not too good at this stuff but learning :)

**Comment by MacWarrior** [comment]
No problem

I close the issue
