### ISSUE TITLE
Remote upload is not working

### ISSUE THREAD

**Issue by anhthoai** [MacWarrior/clipbucket-5.0#40]
Hello. I found remote upload from url is not working, videos are not downloaded to server.

**Comment by MacWarrior** [comment]
Hi,

Do you have any php error ?

**Comment by anhthoai** [comment]
No. I don't see any error there

**Comment by MacWarrior** [comment]
Hi, 

This seems to be a JS related error : 
![capture](https://user-images.githubusercontent.com/200590/41929758-6140582e-7979-11e8-98cb-a6d4f4e20ede.PNG)

**Comment by MacWarrior** [comment]
Hi, 

Please update to this commit for fix : 47600de59d71b3894420922754ac8cbb9d9e6dd8
I didn't tested the full remote upload process, but at least there's no more JS error ;)
