### ISSUE TITLE
https://www.com/admin_area/cb_mod_check.php 500 error ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#43]
hi when i go to https://mysite.com/admin_area/cb_mod_check.php

it throws 500 error any reason why ? i have setup php5.6 and videos upload and also photos upload? 
i dont find error anywhere to check this, what path might be error for this ?
or is this on your end also you see the same 500 error
thanks

Spiro

**Comment by MacWarrior** [comment]
Hi, 
This page works well on my side ; I really need your PHP error to fix it.
Are you up-to-date ?

**Comment by spirogg** [comment]
I uploaded 2 hours ago from GitHub and did fresh install.

**Comment by spirogg** [comment]
How to find phone log error. Where is log in centos 7 ?

**Comment by MacWarrior** [comment]
Hi, 
Your error log filepath is defined in your Vhost configuration ; /var/log/apache2/ by default on apache, per example

**Comment by MacWarrior** [comment]
Can you upload or copy/paste your current cb_mod_check.php ?

**Comment by spirogg** [comment]
[Fri Sep 14 13:07:51.447332 2018] [cgid:error] [pid 20520:tid 140262072309504] [client 0.0.20.5:0] Script timed out before returning headers: ea-php56, referer: https://mysite.com/admin_area/cb_server_conf_info.php

**Comment by spirogg** [comment]
```
<?php
/* 
 ***************************************************************
 | Copyright (c) 2007-2008 Clip-Bucket.com. All rights reserved.
 | @ Author : ArslanHassan										
 | @ Software : ClipBucket , © PHPBucket.com					
 ****************************************************************
*/
require'../includes/admin_config.php';
$userquery->admin_login_check();
$pages->page_redir();
/* Assigning page and subpage */
if(!defined('MAIN_PAGE')){
	define('MAIN_PAGE', 'Tool Box');
}
if(!defined('SUB_PAGE')){
	define('SUB_PAGE', 'Server Modules Info');
}
$ffmpegVersion = check_ffmpeg("ffmpeg");
assign("ffmpegVersion", $ffmpegVersion);
$phpVersion = check_php_cli("php");
assign("phpVersion", $phpVersion);
$MP4BoxVersion = check_mp4box("MP4Box");
assign("MP4BoxVersion", $MP4BoxVersion);
$imagick_version = check_imagick("i_magick");
assign("imagick_version",$imagick_version);
$media_info = check_media_info('media_info');
assign("media_info", $media_info);
$ffprobe_path = check_ffprobe_path('ffprobe_path');
assign("ffprobe_path", $ffprobe_path);
subtitle("ClipBucket Server Module Checker");
template_files("cb_mod_check.html");
display_it();
?>
```

**Comment by MacWarrior** [comment]
Hi,
This is not the file from my fork, please see : https://github.com/MacWarrior/clipbucket-5.0/blob/master/upload/admin_area/cb_mod_check.php

**Comment by spirogg** [comment]
This page isn’t working
mi.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by spirogg** [comment]
@MacWarrior i uploade that file i forgot I tried to change with cb file just to see if make a difference, but now i uploaded again that file and still 500 error

anyway I can give you access to cpanel or whm and you can see for error why this is give me 500 error
i use centos 7 apache latest php 5.6 suphp and tried cgi for phphandler see photo
![capture](https://user-images.githubusercontent.com/17736688/45578271-0d96ac80-b846-11e8-904b-219cf9e8323b.JPG)

**Comment by spirogg** [comment]
what permissions you have this file 644 or 755

**Comment by spirogg** [comment]
#4 was the issue with cpanel and centos 7
