### ISSUE TITLE
when change user to guru or comedian the birth date changes see photos

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#44]
if i make my birthdate 09-08-1998 or whatever birthdate and then save then change guru to comedian or something else the birth date changes doesn't save
in user account settings

![capture](https://user-images.githubusercontent.com/17736688/45571186-13cb5f80-b82b-11e8-84af-3d1f6535a9d7.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45571187-13cb5f80-b82b-11e8-91b4-33f9a917cd0f.JPG)

**Comment by MacWarrior** [comment]
Hi
On my side, I think of a date format error while saving the date ; checking it

**Comment by MacWarrior** [comment]
Hi, 
Fixed in this commit : 999558197848001663199cb031205e09e48b533d
