### ISSUE TITLE
your option for chromcast not working on  video uploads

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#46]
i have check mark chromecast
see photo not working

![capture](https://user-images.githubusercontent.com/17736688/45579736-d75e2a80-b84f-11e8-82c8-373197f77caf.JPG)

**Comment by MacWarrior** [comment]
Hi,
I'm pretty sure it works well on "Generate All" ; will check on SD/HD

**Comment by MacWarrior** [comment]
Fixed in this commit : 571e49e4b400cf53f37709cd8da58a315c079392
