### ISSUE TITLE
is language file broken ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#47]
i see>>>  language file issues

on the website everywhere in drop downs in video container etc

![capture](https://user-images.githubusercontent.com/17736688/45580144-7c2e3700-b853-11e8-8b76-e87aec2aea68.JPG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/45580210-450c5580-b854-11e8-989f-461f477b4e44.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45580211-450c5580-b854-11e8-89c3-d5cfc82349ab.JPG)
![capture2](https://user-images.githubusercontent.com/17736688/45580212-45a4ec00-b854-11e8-9988-06b62b2a303a.JPG)

**Comment by spirogg** [comment]
![capture4](https://user-images.githubusercontent.com/17736688/45580215-4b9acd00-b854-11e8-932a-c94a6f09fd03.JPG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/45580250-a9c7b000-b854-11e8-99d7-b0b7013db7e4.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45580251-a9c7b000-b854-11e8-9159-3fa1d3a2df3a.JPG)
![capture2](https://user-images.githubusercontent.com/17736688/45580252-a9c7b000-b854-11e8-89dd-9ca946262079.JPG)

**Comment by MacWarrior** [comment]
Hi, 
I've already had this kind of issue, will check

**Comment by MacWarrior** [comment]
Fixed in this commit : e3c441f9fa3c2f244e0a5f67717245e04cc803ec
