### ISSUE TITLE
Main Page not loading properly

### ISSUE THREAD

**Issue by aarna63** [MacWarrior/clipbucket-5.0#48]
Hi,

Just installed the clipbucket, but the pages are not loading properly, seems it is not picking up the css.

![image](https://user-images.githubusercontent.com/43074792/45586911-b8c56580-b91b-11e8-8813-1e049adcbd74.png)

**Comment by aarna63** [comment]
Request you revert immediately.

**Comment by MacWarrior** [comment]
Hi
Please be more precise : no technical information = no debug for this kind of problem.
I guess it's a server configuration issue

What I need : 
- Browser console errors
- PHP error logs related
- Did you used my installation script ?

**Comment by aarna63** [comment]
Its done now.

There were issues with webserver configuration.
