### ISSUE TITLE
Video Upload Issue

### ISSUE THREAD

**Issue by aarna63** [MacWarrior/clipbucket-5.0#49]
I am uploading the videos and those videos are being shown in the files folder but I am not able to see the uploaded videos in the admin area nor on the home page.

**Comment by MacWarrior** [comment]
Hi, 
Please upload at least screenshots and give the related PHP errors
I guess it's again a server configuration issue

**Comment by aarna63** [comment]
Share me the file and folder from where I should provide the error.

**Comment by aarna63** [comment]
guide me to share you the error file. From which folder I should provide it.

**Comment by aarna63** [comment]
Pls find the log file.




==========================================

	Pre-Check Configurations

==========================================

File to be converted
--------------------
		Initializing File <strong>1537020762f2763.mp4</strong> and pre checking configurations...

System hardware Information
---------------------------
		H/W path    Device  Class      Description
==========================================
                    system     Computer
/0                  bus        Motherboard
/0/0                memory     3693MiB System memory
/0/1                processor  Intel(R) Xeon(R) CPU @ 2.30GHz
/0/100              bridge     440FX - 82441FX PMC [Natoma]
/0/100/1            bridge     82371AB/EB/MB PIIX4 ISA
/0/100/1.3          bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/3            generic    Virtio SCSI
/0/100/4    ens4    network    Virtio network device


Temporary Uploading
-------------------
		File Uploaded to Temp directory successfully and video conversion file is being executed !

Video Conversion File Execution
-------------------------------
		Video Converson File executed successfully with Target File > !1537020762f2763.mp4



==========================================

	Starting Conversion Log

==========================================

Getting Arguments
-----------------
		Filename : 1537020762f2763.mp4
File directory : 2018/09/15
Log file : /var/www/html/clipbucket/files/logs/2018/09/15/1537020762f2763.log


Conversion queue
----------------
		Getting the file information from the queue for conversion

Conversion queue
----------------
		File has been moved from temporary dir to Conversion Queue

Parsing FFmpeg Configurations
-----------------------------
		<strong>use_video_rate</strong> : 1
<strong>use_video_bit_rate</strong> : 1
<strong>use_audio_rate</strong> : 1
<strong>use_audio_bit_rate</strong> : 1
<strong>use_audio_codec</strong> : 1
<strong>use_video_codec</strong> : 1
<strong>format</strong> : mp4
<strong>video_codec</strong> : libx264
<strong>audio_codec</strong> : libfdk_aac
<strong>audio_rate</strong> : 22050
<strong>audio_bitrate</strong> : 128000
<strong>video_rate</strong> : 25
<strong>video_bitrate</strong> : 4096000
<strong>video_bitrate_hd</strong> : 4096000
<strong>normal_res</strong> : 
<strong>high_res</strong> : 
<strong>max_video_duration</strong> : 320
<strong>resize</strong> : max
<strong>outputPath</strong> : 2018/09/15/
<strong>cb_combo_res</strong> : no
<strong>gen_240</strong> : yes
<strong>gen_360</strong> : yes
<strong>gen_480</strong> : yes
<strong>gen_720</strong> : 
<strong>gen_1080</strong> : 


Starting Conversion
-------------------
		Started on 2018-09-15 14:12:48 - 2018 Sep 15

Checking File...
File : /var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4

File Exists
-----------
		Yes

Preparing file...
-----------------
		<strong>format</strong> : mov,mp4,m4a,3gp,3g2,mj2
<strong>duration</strong> : 10.08
<strong>size</strong> : 6398123
<strong>bitrate</strong> : 5076196
<strong>video_width</strong> : 1920
<strong>video_height</strong> : 1080
<strong>video_wh_ratio</strong> : 1.7777777777778
<strong>video_codec</strong> : h264
<strong>video_rate</strong> : 24
<strong>video_bitrate</strong> : 4695084
<strong>video_color</strong> : N/A
<strong>audio_codec</strong> : aac
<strong>audio_bitrate</strong> : 317375
<strong>audio_rate</strong> : 48000
<strong>audio_channels</strong> : 2
<strong>path</strong> : /var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4
<strong>rotation</strong> : 0


Thumbs Generation
-----------------
		Starting

Thumbs Files
------------
		
 ====== End : Thumbs Generation ======= 


Conversion Ouput
----------------
		

=======Low Resolution Conversion=======


 Sarting : Generating Low resolution video @ 2018-09-15 14:12:49 

 Converting Video SD File  

 Command : /usr/local/bin/ffmpeg -i /var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4 -vcodec libx264 -acodec aac -ac 2 -s 1920x1080 -preset medium -f mp4 -vb 4096000 -ab 128000 -r 25 -ar 22050 /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4 

 ffmpeg output : ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2018-08-14 11:13:56
  Duration: 00:00:10.08, start: 0.000000, bitrate: 5076 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 4695 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2018-08-14 11:13:56
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2018-08-14 11:13:56
      handler_name    : Alias Data Handler
[libx264 @ 0xbbf720] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0xbbf720] profile High, level 4.0
[libx264 @ 0xbbf720] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=4096 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[aac @ 0xccd720] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[libx264 @ 0xbbf720] final ratefactor: 19.70
 

 outputFile : /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4 

 Sarting : MP4Box Conversion for SD 

 MP4Box Command : /usr/local/bin/MP4Box -inter 0.5 /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4  -tmp /var/www/html/clipbucket/files/temp 

 output : Error opening file /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4: IsoMedia File is truncated
 

 Conversion Status : Successful @ 2018-09-15 14:12:49 


OutPut Deatils
--------------
		<strong>format</strong> : 
<strong>duration</strong> : 0
<strong>size</strong> : 0
<strong>bitrate</strong> : 0
<strong>video_width</strong> : 0
<strong>video_height</strong> : 0
<strong>video_wh_ratio</strong> : N/A
<strong>video_codec</strong> : 
<strong>video_rate</strong> : 
<strong>video_bitrate</strong> : 0
<strong>video_color</strong> : N/A
<strong>audio_codec</strong> : 
<strong>audio_bitrate</strong> : 0
<strong>audio_rate</strong> : 0
<strong>audio_channels</strong> : 0
<strong>path</strong> : /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4
<strong>rotation</strong> : 0


Conversion Ouput
----------------
		

=======Low Resolution Conversion=======


 Sarting : Generating Low resolution video @ 2018-09-15 14:12:49 

 Converting Video SD File  

 Command : /usr/local/bin/ffmpeg -i /var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4 -vcodec libx264 -acodec aac -ac 2 -s 1920x1080 -preset medium -f mp4 -vb 4096000 -ab 128000 -r 25 -ar 22050 /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4 

 ffmpeg output : ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2018-08-14 11:13:56
  Duration: 00:00:10.08, start: 0.000000, bitrate: 5076 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 4695 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2018-08-14 11:13:56
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2018-08-14 11:13:56
      handler_name    : Alias Data Handler
[libx264 @ 0xbbf720] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0xbbf720] profile High, level 4.0
[libx264 @ 0xbbf720] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=4096 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[aac @ 0xccd720] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[libx264 @ 0xbbf720] final ratefactor: 19.70
 

 outputFile : /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4 

 Sarting : MP4Box Conversion for SD 

 MP4Box Command : /usr/local/bin/MP4Box -inter 0.5 /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4  -tmp /var/www/html/clipbucket/files/temp 

 output : Error opening file /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4: IsoMedia File is truncated
 

 Conversion Status : Successful @ 2018-09-15 14:12:49 


=======High Resolution Conversion=======


 Sarting : Generating high resolution video @ 2018-09-15 14:12:49

 Converting Video HD File   

 Command : /usr/local/bin/ffmpeg -i /var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4 -vcodec libx264 -acodec aac -ac 2 -s 1920x1080 -preset slow -f mp4 -vb 4096000 -ab 128000 -r 25 -ar 22050 /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-hd.mp4 > /var/www/html/clipbucket/files/temp/1537020762f2763.tmp 

 ffmpeg output : ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/html/clipbucket/files/conversion_queue/1537020762f2763.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2018-08-14 11:13:56
  Duration: 00:00:10.08, start: 0.000000, bitrate: 5076 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 4695 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2018-08-14 11:13:56
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2018-08-14 11:13:56
      handler_name    : Alias Data Handler
[libx264 @ 0x1be6720] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x1be6720] profile High, level 5.0
[libx264 @ 0x1be6720] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=umh subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=abr mbtree=1 bitrate=4096 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[aac @ 0x1cf4720] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[libx264 @ 0x1be6720] final ratefactor: 19.70
 

 Sarting : MP4Box Conversion for HD 

 MP4Box Command : /usr/local/bin/MP4Box -inter 0.5 /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-hd.mp4  -tmp /var/www/html/clipbucket/files/temp 

 output : Error opening file /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-hd.mp4: IsoMedia File is truncated
 

 Conversion Status : Successful @ 2018-09-15 14:12:50


OutPut Deatils
--------------
		<strong>format</strong> : 
<strong>duration</strong> : 0
<strong>size</strong> : 0
<strong>bitrate</strong> : 0
<strong>video_width</strong> : 0
<strong>video_height</strong> : 0
<strong>video_wh_ratio</strong> : N/A
<strong>video_codec</strong> : 
<strong>video_rate</strong> : 
<strong>video_bitrate</strong> : 0
<strong>video_color</strong> : N/A
<strong>audio_codec</strong> : 
<strong>audio_bitrate</strong> : 0
<strong>audio_rate</strong> : 0
<strong>audio_channels</strong> : 0
<strong>path</strong> : /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-hd.mp4
<strong>rotation</strong> : 0


Conversion Completed
--------------------
		
 ====== End : Thumbs Generation ======= 


Time Took : 2.4994 seconds

conversion_status : failed

**Comment by MacWarrior** [comment]
Hi

"output : Error opening file /var/www/html/clipbucket/files/videos/2018/09/15//1537020762f2763-sd.mp4: IsoMedia File is truncated"

Please try another file to import ; this one seems to be corrupted
Do you have enough space on your HDD ?
Did you restart apache during the convertion process ?
Please upload a screenshot of : Admin > Tool Box > Server Modules Info

**Comment by aarna63** [comment]
Have enough space on the server.

Pls find the screenshot.

![image](https://user-images.githubusercontent.com/43074792/45587771-1cee2680-b928-11e8-871a-dc70adfd5317.png)

**Comment by aarna63** [comment]
I upgraded the FFMPEG, but still showing the video, with a recent upload.

**Comment by MacWarrior** [comment]
Can you upload a website home screenshot and a admin video listing screenshot ?

**Comment by aarna63** [comment]
![image](https://user-images.githubusercontent.com/43074792/45588275-d0a6e480-b92f-11e8-907b-5aa0b5b19240.png)


![image](https://user-images.githubusercontent.com/43074792/45588283-ec11ef80-b92f-11e8-919e-93870610b681.png)


![image](https://user-images.githubusercontent.com/43074792/45588285-fdf39280-b92f-11e8-9d0d-27ce159d5c07.png)

**Comment by MacWarrior** [comment]
You have 2 problems : 
1) Videos don't appear in video manager : for some unknow reason, PHP/SQL can't save the video your uploading : did you use video upload or mass upload ?
Did you get any error in your php log file (Default is /var/log/apache2/* if you use apache)
2) Videos aren't converted correctly, the main file seems to be corrupted : did you try another file ?
Can you try "Generate All" instead of "Generate SD HD" in General > Website Configurations > Uploading and conversion settings

**Comment by aarna63** [comment]
After upgrading the FFMPEG, the videos files are being generated in the files folder and after turing on the "Generate All", it is preparing 5 video files.

But is still doesnot display on the web page or on the video manager page. Apart from this, as the videos are generated, in the queue manager, is shows processing, as the video files has been processed.

Sharing the screenshot and log files.

[Logs.zip](https://github.com/MacWarrior/clipbucket-5.0/files/2386384/Logs.zip)

![image](https://user-images.githubusercontent.com/43074792/45594090-3d62c300-b9b2-11e8-9f27-cacb04f8741d.png)

**Comment by MacWarrior** [comment]
Hi,
Did you checked your PHP error file ? 
By default : /var/log/apache2/
You may have specified a custom one in your vhost config

While and after uploading a video : do you see some ffmpeg process in your process list ? (top // htop)

**Comment by MacWarrior** [comment]
Hi,

For information, in your logs : 
```
[Sun Sep 16 03:26:36.840024 2018] [:error] [pid 5527] [client 202.29.239.19:26006] script '/var/www/html/clipbucket/boots.php' not found or unable to stat
[Sun Sep 16 03:26:37.347195 2018] [:error] [pid 5529] [client 202.29.239.19:26143] script '/var/www/html/clipbucket/she.php' not found or unable to stat
[Sun Sep 16 03:26:37.857538 2018] [:error] [pid 1879] [client 202.29.239.19:26276] script '/var/www/html/clipbucket/s.php' not found or unable to stat
[Sun Sep 16 03:26:38.364997 2018] [:error] [pid 5530] [client 202.29.239.19:26399] script '/var/www/html/clipbucket/qw.php' not found or unable to stat
[Sun Sep 16 03:26:38.872643 2018] [:error] [pid 1875] [client 202.29.239.19:26518] script '/var/www/html/clipbucket/test.php' not found or unable to stat
```
Some script kiddie tried to hack you ? Or maybe juste one of your tests ?

The "Missing translation for..." indicate you're in development mode ; can you try disabling it ?

Can you also check your PHP-CLI configuration ? In my case, I had to manually enable error logs (Debian 9, PHP 7.0)

**Comment by chinli12** [comment]
I have the same issue please can you show us server installation guild we will be glad

**Comment by chinli12** [comment]
I was able to solve the problem Chang your audio codec to aac in video conversion setting

**Comment by MacWarrior** [comment]
Hi,

Thanks for reply, this must be related to your ffmpeg version
I will add a verification on audio / video codecs before conversion

**Comment by MacWarrior** [comment]
Note : for compatibility purpose, you should really try to fix your ffmpeg environment to be able to use AAC audio codec

**Comment by MacWarrior** [comment]
Hi,

I already made a verification before conversion, but there can be a bug in it ; can you type this commande on your server and give me the return : 
```ffmpeg -codecs 2>/dev/null | grep 'aac'```

**Comment by chinli12** [comment]
![screenshot_2018-09-29-12-54-14](https://user-images.githubusercontent.com/29612076/46245655-48254b00-c3e9-11e8-9056-2731ddca9678.png)

**Comment by MacWarrior** [comment]
@chinli12 : I badly understood your reply ; it works by using the AAC audio codec ; what was used before ?
Your screenshot is coherent with the use of AAC : ffmpeg allows it
I don't know for any plugins because I use none ; you can create a test environment and test by yourself

@aarna63 : Can you execute ```ffmpeg -codecs 2>/dev/null | grep 'aac'``` on your server and return the results ?
