### ISSUE TITLE
subscribe not working , using any subscribe button admin to user or user to admin

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#51]
hi when clicking on subscribe in the photos, videos user profile sectcion, will not subscribe

**Comment by spirogg** [comment]
![1subscribe](https://user-images.githubusercontent.com/17736688/45601151-ef5bb880-b9cd-11e8-831b-39191d4b8ce9.JPG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/45601154-069aa600-b9ce-11e8-9e64-ec5f784a6924.JPG)

**Comment by spirogg** [comment]
I have set allowed to subscribe in the user section, but still not working

**Comment by spirogg** [comment]
![capture1](https://user-images.githubusercontent.com/17736688/45601245-912fd500-b9cf-11e8-8b23-a219f2ccca08.JPG)

**Comment by spirogg** [comment]
this happens on all the subscribe buttons, in different pages just fyi  thank you @MacWarrior 

your latest revision if SO AWESOME !!! your are Awesome programmer :) 👍 💯 🥇

**Comment by MacWarrior** [comment]
Hi,

I was reproducing, but no php error log ; so I started by cleaning up the ajax.php file
I don't know what I exactly did but this is fixed in this commit :lol: : b59ae713ea79d31ce3ea6d5a71a88b16f020392e
