### ISSUE TITLE
share photo direct link not correct

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#52]
![capture](https://user-images.githubusercontent.com/17736688/45601154-069aa600-b9ce-11e8-9e64-ec5f784a6924.JPG)

**Comment by MacWarrior** [comment]
Hi, 

In my case, elements here are wrong (All links to image file)

The share this photo function is hardcoded yet, not sure if fully functionnal ; will try to fix / implement

**Comment by MacWarrior** [comment]
Hi, 

Sharing links fixed in this commit : cec179e0390bea371b82e196de03e342d6788977

**Comment by MacWarrior** [comment]
Hi, 

As I thought, suggested users isn't implemented : it might be used to select friends

In My account > Contacts Manager, did you see anywhere to add a friend ? Or sending a friend request ?

**Comment by MacWarrior** [comment]
My bad, I saw the "Add as friend" on the channel page

**Comment by MacWarrior** [comment]
Hi, 

Users suggestion implemented in this commit : 3771b040c96321b1bd74deb5802cf882707d430e

(For any email/notification error (which I didn't test yet), please create another issue)
