### ISSUE TITLE
Ubuntu 18.04 Installer

### ISSUE THREAD

**Issue by miasmaejuices** [MacWarrior/clipbucket-5.0#58]
Hi.

I don't know if it's helpful, but I've used your installer scripts and created an updated version for Ubuntu 18.04.  You can find it here: https://pastebin.com/ubNeuEeL

You'll note a couple of things that are required to make it work:

- Added `universe` to allow installation of applications like MariaDB
- Updated to use `php7.2` instead of `php7.1`
- Moved install directory to `/var/www/clipbucket/` to bring it more into line with current system layouts
- Added softlinks to FFMPEG and MP4Box, so the ClipBucket config is no longer required
- Disabled the `000-default` Apache conf
- Enabled Apache module `rewrite`

I hope this helps others.

Thanks!

**Comment by MacWarrior** [comment]
Hi, 
Thanks for your participation ; I'll test it soon and merge if everything is OK.

Correct me if I'm wrong but on Debian per example (9.X), installing "mysql-server" is installing mariaDB ; isn't it the same on Ubuntu ? In that case, the repo modification isn't really requiered.

**Comment by miasmaejuices** [comment]
According to the [MariaDB website](https://downloads.mariadb.org/mariadb/repositories/#mirror=aarnet_pty_ltd&distro=Ubuntu&distro_release=bionic--ubuntu_bionic&version=10.1), MariaDB is included in the default Ubuntu 18.04 repositories.

What it _doesn't_ tell you is that the repository in question is the `universe` repo, as it's provided by a 3rd party and supported by the community.  It's not considered core Ubuntu, where MySQL is (the information is a bit old now, but you can find out about the Main; Restricted and Universe repos [here](https://www.howtogeek.com/194247/whats-the-difference-between-main-restricted-universe-and-multiverse-on-ubuntu/)).  I cant recall if it has always been that way, or if it was moved out of Main in recent years.

When you try and install `apt install mariadb-server` from the cli on a fresh install of Ubuntu, you get a `package cannot be found` error. Enabling the `universe` repo resolves the issue.

I'm about to retest the script, I want to make sure it's working and I'll report back.

**Comment by miasmaejuices** [comment]
Also, as there is no real way to use `apt` properly in a script, it throws errors which can safely be ignored.  `apt-get` might be preferable, but it's no longer the standard method of installation for packages.

**Comment by miasmaejuices** [comment]
Ok, just tested again.  The script did as it was supposed too (with the `apt` errors), but passed through the installation and configuration properly on a clean system.

I look forward to hearing your thoughts. :)

**Comment by MacWarrior** [comment]
Hi, 

Thanks for your replies ; I mainly work on Debian so I'm not aware of the latests standards of Ubuntu
When I made this script, I just tested the site was running well, it's based on the Debian one

**Comment by miasmaejuices** [comment]
That's cool, I totally understand.

Would you like me to go back and test the other scripts for Ubuntu as well?

**Comment by miasmaejuices** [comment]
No problems, give me a few days, I'll report back.

I'll try and include any required adjustments as well.

**Comment by MacWarrior** [comment]
Hi, 

Ubuntu 18.04 installation script commited : c8379123f45929663823b6f881bfa76afe0cb8a5
Can you please open new issue or merge request for others scripts updates ?

Thanks again

**Comment by miasmaejuices** [comment]
No problems. Will do 😊
