### ISSUE TITLE
[Feature Request] - Add `webm` and `mkv` to default file types

### ISSUE THREAD

**Issue by miasmaejuices** [MacWarrior/clipbucket-5.0#59]
As the title says, `webm` and `mkv` are common file types.

`webm` usually contains VP8 or VP9 which are supported directly by FFMPEG now - I've tested and both transcode correctly.

`mkv` contains codecs that are used in the `mp4` container.  MPEG4; x.264; HEVC etc.  All have been tested and function correctly.

No core code changes are required, just the default file types.

Thanks :)

**Comment by MacWarrior** [comment]
Hi,

I've made therse additions on my own server, will add them on the repo

**Comment by MacWarrior** [comment]
Hi, 

Done in this commit : 3a53d1116c9268a23bcfbfdf0e009113d50ad3a0
