### ISSUE TITLE
User Registration Error: Please Select Your Category

### ISSUE THREAD

**Issue by miasmaejuices** [MacWarrior/clipbucket-5.0#60]
User registration error received when creating new users using the front end:

![capture](https://user-images.githubusercontent.com/33153516/45794656-ab2d2880-bceb-11e8-8ef0-9743859def4a.PNG)

And also from the admin panel:

![capture2](https://user-images.githubusercontent.com/33153516/45794666-b2543680-bceb-11e8-8695-ce98e9dac63e.PNG)

For reference, here are my categories:

![capture3](https://user-images.githubusercontent.com/33153516/45794670-baac7180-bceb-11e8-8c82-f2028ef68814.PNG)

**Comment by MacWarrior** [comment]
Hi,

Did you made any user category modification between screen ? 
Because on my side, all select input display the same thing and I can't reproduce your error : users are created correctly

**Comment by MacWarrior** [comment]
Hi,

There is an existing android app ? Or are you asking for a correct mobile support ?

**Comment by miasmaejuices** [comment]
You didn't know? Well, let me edumicate ya! Hehe!
https://play.google.com/store/apps/details?id=com.clipbucket&hl=en

**Comment by miasmaejuices** [comment]
Ok, just retested with a completely clean installation:

![capture](https://user-images.githubusercontent.com/33153516/45852622-d586f080-bd94-11e8-953b-daa00c0f666b.PNG)

**Comment by MacWarrior** [comment]
1) Got some free time this week, will work on fixes
2) CB also available on iOS, testing it (But if it's more than a dedicated web browser, I won't be able to do anything...)

**Comment by MacWarrior** [comment]
And as I see, an API module is requiered...

Personnally, I really prefer a good mobile-friendly website instead of this kind of app, and this is in my TODO

**Comment by MacWarrior** [comment]
Hi, 

There was an error on the user's category saving process
Can you retry with last fix : b7c9bc40f2c2709f5876311cb91ca7775b74bb64 ?

**Comment by miasmaejuices** [comment]
Will reinstall today to test.  :)

**Comment by miasmaejuices** [comment]
> 
> 
> Hi,
> 
> There was an error on the user's category saving process
> Can you retry with last fix : [b7c9bc4](https://github.com/MacWarrior/clipbucket-5.0/commit/b7c9bc40f2c2709f5876311cb91ca7775b74bb64) ?

Just tested - Error still remains.

Im seeing this in the Apache logs, could this be related?

```
[Tue Sep 25 03:08:50.999959 2018] [php7:notice] [pid 15583] [client 192.168.86.27:56737] [LANG] Missing translation for "user_name_invalid_len", referer: http://192.168.86.101/signup.php
[Tue Sep 25 03:08:51.000052 2018] [php7:notice] [pid 15583] [client 192.168.86.27:56737] [LANG] Missing translation for "username_spaces", referer: http://192.168.86.101/signup.php
```

**Comment by MacWarrior** [comment]
Hi,

Therse errors are for debug purpose and only available in dev mode ; don't worry about this :)

Doing a full reinstall, if I can't reproduce, I can't fix :(

**Comment by MacWarrior** [comment]
Tested on a clean default install : works fine by my side with the exact same informations specified on the inscription screenshot you made (Except for the user category, I used the default one)

On your screenshots, I see you have only one user category : Basic User ; in this configuration, BGC and AB aren't existing categories : did you do some HTML edit to have therse listed ?

**Comment by miasmaejuices** [comment]
I've wiped the machine completely, and reinstalled the OS from scratch.  Instead of screenshots, I thought it would be better illustrated in a video.

I've posted it [here for you](https://peertube.mastodon.host/videos/watch/08bbdaef-202b-4d33-a489-2612c6d960a2).

Keep in mind, this is completely from scratch, no changes to any code.

**Comment by MacWarrior** [comment]
Hi, 

Thanks, will watch it

Correction to my previous comment : the [LANG] error is always display, it indicate missing translations (But there is a more complete log when in development mode)

**Comment by MacWarrior** [comment]
Thanks for the video ; I confirm you did nothing wrong, but the BCG category isn't something created by default ; can you try another browser to check some cache/plugin related issue ?

**Comment by MacWarrior** [comment]
Can you check your DB to see if you see any BCG insert somewhere ?

**Comment by MacWarrior** [comment]
Do you have any possibility to provide a temporary public access + back office access ?

**Comment by miasmaejuices** [comment]
> 
> 
> Do you have any possibility to provide a temporary public access + back office access ?

Unfortunately, it's all internal.  I'm testing it as an alternative to YouTube for my kids.  It'll allow me to control what they can have access too.

I'm just installing PHPMyAdmin to browse the database.

**Comment by miasmaejuices** [comment]
Well that's interesting.  I just got an error in PHPMyAdmin: `count(): Parameter must be an array or an object that implements Countable`

Let me try reverting to MySQL instead of MariaDB...

**Comment by MacWarrior** [comment]
PHPMyAdmin isn't related to the main problem, and except if you're using some special MariaDB version, it should work fine (I only work on MariaDB)

**Comment by miasmaejuices** [comment]
Could it be the version of PHP?  I'm running 7.2 as it's the default in later version of Ubuntu.

**Comment by MacWarrior** [comment]
Good point, will re-test PHP 7.2

**Comment by MacWarrior** [comment]
What version of Ubuntu ?

**Comment by miasmaejuices** [comment]
> 
> 
> What version of Ubuntu ?

I'm testing with Ubuntu 18.04 LTS.

I'll try rolling back to PHP 7.1 and 7.0.

**Comment by MacWarrior** [comment]
Ok, thanks
Downloading Ubuntu 18.04 for testing

**Comment by miasmaejuices** [comment]
Right - Initial test of PHP 7.0: Working, though different errors now, probably due to not using a fresh reinstall.

Testing 7.1 now.

**Comment by miasmaejuices** [comment]
Ok, confirmed that CB will not work on PHP 7.1 or 7.2 on Ubuntu 18.04 64bit.

Downgrading to 7.0 will allow it to run properly.

**Comment by MacWarrior** [comment]
Thanks for information, I used to made fixes for 7.1 and 7.2 ; will test again both

**Comment by lucassica** [comment]
YOU HAVE TO REINSTALL

FIRST CHANGE PHP VERSION THEN INSTALL CB
________________________________

**Comment by MacWarrior** [comment]
Hi,

Can you please retry with PHP 7.1+ and this commit : bb283a5249331948b62e72f1118e587b5cb52ff9
The dropdown menu is now correct on PHP 7.2 by my side

**Comment by miasmaejuices** [comment]
> 
> 
> Hi,
> 
> Can you please retry with PHP 7.1+ and this commit : [bb283a5](https://github.com/MacWarrior/clipbucket-5.0/commit/bb283a5249331948b62e72f1118e587b5cb52ff9)
> The dropdown menu is now correct on PHP 7.2 by my side

That seems to have solved this particular issue.  Moving to PHP7.2 seems to have introduced a few other issues.  I'll post new issues as I find them.  Good work mate :)

**Comment by MacWarrior** [comment]
Hi,

When I worked on PHP 7.1+ compatibility, I only fixed technical errors ; any functionnal issue is welcome 😉 

Thanks for your time testing !

**Comment by lobosdesigns** [comment]
has there been a fix yet. My host only has 7.2 php and the catagories doesnt work. Can someone plz post a fix

**Comment by lodhja** [comment]
I am facing the same problem too. I have tried fresh installs with php7.2 and php7.3 in ubuntu 18.04. The categories are displayed only with php7.0 but no user is created at all! I am with php7.3 now and I see only this strange category "ABGC". It is not a category in db.
Any solution with the categories?

**Comment by MacWarrior** [comment]
Hi
I reopen the issue for testing ; I haven't tested latests PHP versions yet, will try soon

**Comment by lodhja** [comment]
Perhaps solved as indicated also by MacWarrior.
In fact I am using the official version 4.2 RC1 and to display the categories I just replace the following in line 427 of upload/includes/classes/form.class.php

$field['value'] = '';
with
$field['value'] = array();

The categories are displayed OK but now I am getting the following error when I try to submit the request to create new user!
 **Invalid 'email'**

Any idea on this?

**Comment by MacWarrior** [comment]
Hi,
I'm currently setting up a Debian 10 + PHP 7.3 VM to test compatibility

If you're using the official repo, this kind of error is normal because of the more limited PHP compatibility ; in this case, please submit report on official repo for official answers

**Comment by lodhja** [comment]
Consider that I tried your "MacWarrior" version also and faced the same problems. 
Thanks MacWarrior

**Comment by MacWarrior** [comment]
Hi,
I can confirm the categories are display correctly with PHP 7.3 on this repo ; can you provide a screenshot without any modification of code from your side ?

About email, I don't have any issue like that ; can you provide a screenshot ?

**Comment by lodhja** [comment]
As I said I am not using this repo but the clipbucket one.

First image is the code without modifications, it displays Category: ABCD, this are the first letter of All, Basic users, Guru, Comedians.
![scl0](https://user-images.githubusercontent.com/37837771/61378828-90452980-a8a6-11e9-8bb3-abdd5aa7bf29.JPG)

Second image after I corrected code. I am still getting **Invalid 'email'** errror!
![scl](https://user-images.githubusercontent.com/37837771/61378924-bd91d780-a8a6-11e9-9978-817251f43965.JPG)

Thanks

**Comment by MacWarrior** [comment]
Hi
Can't reproduce this issue, must be related to original repo : please report on the original repo

**Comment by waptug** [comment]
I am running clipbucket on php 7.2 and getting that pesky category dropdown issue previously reported. MacWarrior/clipbucket-v5#60 . I have created a docker image that works out of the box with all the ffmpeg and such working and installed. ( https://github.com/waptug/geekzonehostingllc-clipbucket-lamp-server ) but still has this issue present.  Hoping that there is progress being made on updating clipbucket to support current php 7.4 and 8

**Comment by MacWarrior** [comment]
Hello @waptug,

It looks like you're using original version of Clipbucket and not this one.
Please replace your sources with this repo to get support here 😄

Best regards,
MacWarrior.

**Comment by waptug** [comment]
Thanks. Did you track your changes you have made in this repo so I can take a look?

**Comment by lobosdesigns** [comment]
I'm no longer using it at all

**Comment by MacWarrior** [comment]
> Thanks. Did you track your changes you have made in this repo so I can take a look?

More than 600 commits, a bit hard to list everything...
Please check changelog files to get an idea : https://github.com/MacWarrior/clipbucket-v5/tree/master/upload/changelog
