### ISSUE TITLE
Video uploading not working

### ISSUE THREAD

**Issue by chinli12** [MacWarrior/clipbucket-5.0#61]
After hostwind tech install clipbucket version 4.1 and they configure all the required software to run clipbucket but video conversion not working  they have try so many way ,please if any thing missing tell me

**Comment by MacWarrior** [comment]
Hi, 

I can't give you support on version 4.1 here, please report on official repo
BTW, we need more informations ; just saying it don't works isn't helpfull, and it works fine on my side :(

**Comment by chinli12** [comment]
Please can you show me installation procedure let me follow and configure the server for the script

**Comment by chinli12** [comment]
I will be very glad if you help me

**Comment by miasmaejuices** [comment]
> 
> 
> Please can you show me installation procedure let me follow and configure the server for the script

Can you provide more information about the operating system you are using?  Linux?  Which Distro?

**Comment by chinli12** [comment]
I am using Linux server Ubuntu 16.4

**Comment by miasmaejuices** [comment]
There is an installer script here: https://github.com/MacWarrior/clipbucket-5.0/blob/master/utils/install_ubuntu16.04.sh

MacWarrior wrote it, and I'm in the process of testing it.  There may need to be some rewrites, so use at your own risk.  If you give me a day or so, I can test it more thoroughly.

**Comment by MacWarrior** [comment]
Hi, 

It may not be perfect, but it works well, I've tested it many times ! (Just saying :wink:)

**Comment by miasmaejuices** [comment]
> 
> 
> Hi,
> 
> It may not be perfect, but it works well, I've tested it many times ! (Just saying 😉)

You did a great job Sir!  No one is doubting that!

I'm only fixing up little issues as I see them, that's all ;)

**Comment by chinli12** [comment]
Please can you check this log to know the issues
[1537484533c28b9.log](https://github.com/MacWarrior/clipbucket-5.0/files/2403502/1537484533c28b9.log)
[1537485958363f7.log](https://github.com/MacWarrior/clipbucket-5.0/files/2403503/1537485958363f7.log)
[1537489143295fc.log](https://github.com/MacWarrior/clipbucket-5.0/files/2403504/1537489143295fc.log)
[1537489585c931e.log](https://github.com/MacWarrior/clipbucket-5.0/files/2403505/1537489585c931e.log)

**Comment by spirogg** [comment]
File doesn't exist. Path: /var/www/html/files/videos/2018/09/21/1537489585c931e-240.mp4 

check your file permissions so they can write 7777 /files/ directory. try change and upload again video see if this helps
