### ISSUE TITLE
Unable to upliad large video size

### ISSUE THREAD

**Issue by chinli12** [MacWarrior/clipbucket-5.0#64]
I was unable to upload a 128mb of video in my clipbucket

**Comment by MacWarrior** [comment]
Hi, 

This is related to your server configuration, not clipbucket 😉 
If you're using PHP : https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size

**Comment by spirogg** [comment]
Are you in server or shared hosting. ??

**Comment by spirogg** [comment]
Did you add in php.ini max upload size or just in .htaccess

**Comment by chinli12** [comment]
I am in server and I add it in php.ini not htacces

**Comment by lucassica** [comment]
http://hotelhoster.com  if you need a hosting
Nuhost - Homepage<http://hotelhoster.com/>
nuhost responsive HTML & WHMCS hosting template
hotelhoster.com


________________________________

**Comment by chinli12** [comment]
Is it good for clipbucket

**Comment by lucassica** [comment]
yes , but  the clipbucket submit button d'ont work on 4.1 and the youtube video upload does not work
________________________________

**Comment by lucassica** [comment]
whats installed http://hotelhoster.com/upload/cb_install/
