### ISSUE TITLE
edit photos from user account area not working

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#70]
when you go to my account >> manage photos 

manage_photos.php
and you click on edit for any photo it takes you to this page and give error not found page

![capture](https://user-images.githubusercontent.com/17736688/46322957-840b0c80-c5b1-11e8-8547-ec347599dbd7.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/46322958-84a3a300-c5b1-11e8-9492-3f8e92e516d7.PNG)

**Comment by spirogg** [comment]
PS in the admin_area the manage photos and edit works, just not for users front end

![capture](https://user-images.githubusercontent.com/17736688/46323013-c0d70380-c5b1-11e8-9b9d-4a088ee95464.PNG)

**Comment by MacWarrior** [comment]
Hi,

I've made a mistake on and old commit by deleting this page
Fixed on last commit
