### ISSUE TITLE
when selecting all (check mark) it doesn't work to select all users in the user flagged area

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#75]
when selecting all (check mark) it doesn't work to select all users in the flagged area

![capture1](https://user-images.githubusercontent.com/17736688/46324473-37c3ca80-c5b9-11e8-8233-e03418d325c0.PNG)

**Comment by MacWarrior** [comment]
Hi,

Fixed in this commit : bf38c715cc5f55c809daeb16b55a69a10a2d9a32
