### ISSUE TITLE
Chrome, firefox, opera browsers do not play processed videos with new player only sound and only edge browsers works ? ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#76]
@MacWarrior 

hi i just reinstalled latest from your repo on github and i installed ffmpeg everything processed ok, but i never tried to play videos on another browser. So now I uninstall all my work for ffmpeg:(

 but there are 2 videos I had uploaded and I just tried and they play on windows 10 edge browser
-  but not on chrome browser, chrome browser only you here the sound and see static image, but no motion in videos ??

- can you check if it's a plugin we need in chrome browsers to view videos ?

- or something wrong with your videojs player ?

can you please check this thanks so much

Spiro

**Comment by spirogg** [comment]
- same for latest firefox doesn't play the videos only here sound ??

**Comment by MacWarrior** [comment]
Hi,
I haven't found any issue of this kind since I updated the player.
On both Chrome and Firefox, everything works fine for me : can you specify which audio/video conversion codec you use (Most are not compatible on all browser)

**Comment by spirogg** [comment]
I was using libfdk_aac
- Can you tell me what your using ?
Then I can make sure I install again these codecs so I can view them. On
app browsers.

Why edge work but not chrome firefox opera ? What coedecs I need to use to
make sure all is working good. ?

- Should.i I stall ffmpeg 2.6.8 instead of 3.x ? What do you think is best.
Stick with nux since I have centos 7 and cpanel ?

- By the way everything seems really solid right now. Other than can't play
videos on browsers.

Thanks so much for fast response


Spiro

**Comment by MacWarrior** [comment]
Hi,

I use libx264(video) and aac(audio), tested right now on Firefox, Chrome & Edge

Do you have any PHP // JS(console) error while trying to play video ?

**Comment by spirogg** [comment]
No errors. What version of ffmpeg you have. I might of asked you this already. 

 I use centos 7 with cpanel. 
Where can I get an install guide to get all required needed for cb to function. I use to have one script. But it's not working any longer. Is there still somewhere I can get ffpmeg etc etc if I use nux from r centos it instoaa 3.8.15 and doesn't have all configuration encourage ders lbfdk-aac and or even aac I don't see it cause I tried already. From yum. 

Is there something you can instruct how to for me.please. I hate when I cusnge servers and loss everything and ffmpeg scripts cusnge. ,:(

**Comment by spirogg** [comment]
By the way. If you celebrate. Merry Christmas to you and your family my
friend. !! :)
Happy holidays. Hope the new year brings plenty of health #1 and plenty of
wealth and happiness
 Appreciate all your hard work. Helping to make this repo really good. :)

**Comment by spirogg** [comment]
chrome://flags/#disable-accelerated-video-decode

**Comment by spirogg** [comment]
- Go to chrome://flags/#disable-accelerated-video-decode
 - Change this option to "Enabled" (which disables Hardware Video Decode)
 - Click the "Restart Chrome" button at the bottom of the page.

Here is link. https://support.google.com/youtube/forum/AAAAiuErobUT6hNpETUu_U/?hl=en

Read First article and click more button you will see the suggestion I wrote above. 


https://support.google.com/youtube/forum/AAAAiuErobUT6hNpETUu_U/?hl=en

**Comment by spirogg** [comment]
![screenshot_20181224-225116](https://user-images.githubusercontent.com/17736688/50412663-e0578400-07ce-11e9-858d-8da99774e1c9.png)

**Comment by spirogg** [comment]
ok the person who configured ffmpeg for me was not configured properly, i installed static build and now its working without any issues :)

sorry to bother you have a great day

**Comment by MacWarrior** [comment]
Hi,
Sorry for late reply, glad to hear the problem is resolved
Merry Christmas to you too
