### ISSUE TITLE
 issue gets stuck on generate all and not switch back to generate SD HD ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#78]
sometimes issue with change back n forth from Generate all Generate SD HD?

if I change Set Video Resolution type 
- Generate All  
- and select any of these options
**Generate 240 | Generate 360 | Generate 480 | Generate 720 | Generate 1080**

- will this work for you on your demo or site ?
---------------------------------------------------------

- I tried it yesterday and it seemed it got stuck ? it would not go back to (Generate SD HD)

could this be cache ? 
or should it just change and work ?

- have you experienced any issues with it sometimes it gets stuck on this option (Generate All) 
and wont go back to SD/HD ? just wondering. 

Im using centos 7 cpanel php7.0

thanks

Spiro

**Comment by MacWarrior** [comment]
Hi,
I never met this kind of issue and it used to work well on my testing environment
I will test both SD/HD and "all" generating options

**Comment by spirogg** [comment]
- It might of been php 5.6 I had set to yesterday or something
- I just tried it with 7.0 now and it seems to be working good :)

you can test on your end just to make sure 💯

**Comment by spirogg** [comment]
ok this works no need to worry i close this ticket
