### ISSUE TITLE
in user channel photo and playlist not working wont change

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#8]
![photo and playlist not working](https://user-images.githubusercontent.com/17736688/40581654-c5524962-6123-11e8-892c-9a76bcc8bed0.PNG)

**Comment by MacWarrior** [comment]
Hi, 

As I understand for now, Photos collections ans Playlists are listed in the current "Videos" tab
It must be just some missing HTML ; will fix it soon.

**Comment by MacWarrior** [comment]
Please update to latest version :)

**Comment by spirogg** [comment]
Hi. To upgrade to latest version. Should I reinstalled. Everything or just upload folders adn files in upload ??

**Comment by MacWarrior** [comment]
Just update files ; no SQL requiered

**Comment by spirogg** [comment]
ok when I First do this update files - I see site is in maintenance mode on top of site? how to fix that after upload files ?
