### ISSUE TITLE
new install not working Nothing is showing for mp4box ffprobe etc

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#80]
hi i just deleted the old one and uploaded fresh install of your repo now and its not working. i cant upload video I have same setting like before in config and its not working ?

**Comment by spirogg** [comment]
ok i set to php5.6 then uploaded and worked now i changed back to php7.2 still working ?? weird

**Comment by spirogg** [comment]
well now I revert to php 7.0 becasue 7.2 wont allow me to click submit to upload photos ? im using cpanel and have all options the same in php options in 7.2 and 7.1 and 7.0 so not sure why its not working with 7.2 to upload photos submit button. ?

5.6 works great and so does  7.0

**Comment by MacWarrior** [comment]
Hi,
Thanks for reply, this is a new PHP 7.2 issue, will fix it asap

**Comment by spirogg** [comment]
just for FYI

5.6 7.0 works photo and video submit button

7.1 and 7.2 can not use submit for photos only 

7.1 and 7.2 submit for videos works just not photo

![capture](https://user-images.githubusercontent.com/17736688/50584811-61e68c00-0e37-11e9-9fe2-c185474e8b2c.PNG)

**Comment by MacWarrior** [comment]
Hi,
I've been working on PHP 7.3.X compatibility and this seems now to be fixed with latest commit
