### ISSUE TITLE
Video comments not working

### ISSUE THREAD

**Issue by MacWarrior** [MacWarrior/clipbucket-5.0#87]
Note to myself : video comments generate JS error

**Comment by spirogg** [comment]
here is photo and video of comment and reply to comment 

using php 7.0 working for video and photo no errors i see

possible same issue with when i first installed and php7.2 and php 7.1 not working #80



- ![capture](https://user-images.githubusercontent.com/17736688/50586850-fef9f280-0e40-11e9-82cc-78684b5b9f4c.PNG)
- ![capture1](https://user-images.githubusercontent.com/17736688/50586855-015c4c80-0e41-11e9-9648-26eddcef90b3.PNG)

**Comment by MacWarrior** [comment]
Hi,

I got a JS error relative to the ajax response, can be related to PHP 7.X compatibility but I must check

**Comment by MacWarrior** [comment]
Hi,
Fixed in last commit
