### ISSUE TITLE
subscribe and unsubscribe working but popup box says no data ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#88]
the popup box should say something like:

You have successfully subscribed 
and 
You have successfully unsubscribed

something like that 

right now it just says:
 no data

see photo

![capture](https://user-images.githubusercontent.com/17736688/50587572-0b337f00-0e44-11e9-94cd-a96374658b98.PNG)

**Comment by MacWarrior** [comment]
Hi,

This may be linked with this commit : 
245e0f30066adc7f51c90517a6acd2b3c970f50e

Are you sure you're up-to-date ?
Can you retry after cleaning your browser cache ?

**Comment by MacWarrior** [comment]
Are you in DEV mode ?
I could have forget to update the .min JS file used out of DEV mode

**Comment by MacWarrior** [comment]
Ok, this is totally that ; will fix it asap

**Comment by MacWarrior** [comment]
Thanks for report !

**Comment by MacWarrior** [comment]
Can you retry with last commit ?

**Comment by spirogg** [comment]
i uploaded last commit and cleared cache even went to cache folder and deleted from there views still same popup box say no data ?

![capture](https://user-images.githubusercontent.com/17736688/50618532-0d83f080-0eb9-11e9-9904-f8fea514670c.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/50618533-0d83f080-0eb9-11e9-9f27-75f10326b256.PNG)

**Comment by spirogg** [comment]
also i just downloaded opera browser to test also and still same thing

![capture](https://user-images.githubusercontent.com/17736688/50618580-81be9400-0eb9-11e9-982b-4a43cca1e36e.PNG)

**Comment by spirogg** [comment]
sorry also opera browser i just downloaded same error

![capture_li](https://user-images.githubusercontent.com/17736688/50618647-ea0d7580-0eb9-11e9-95f4-a4adf15de48a.jpg)

**Comment by spirogg** [comment]
i tried with php5.6 and php 7.0 same issue
- also when you click subscribe or unsubscribe you need to refresh for it to show you are subscribed, not sure if there is a work around on that ?

**Comment by MacWarrior** [comment]
Hi,
Fixed in last commit :smile:
