### ISSUE TITLE
user prifle birthdate not working - saving 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#9]
![date in profile settings not working or saving](https://user-images.githubusercontent.com/17736688/40581695-c822ed94-6124-11e8-8fcb-850b05f93942.PNG)

**Comment by spirogg** [comment]
hope you dont mind if i find bugs and tell you them, hope this helps you and not stress you more :(

**Comment by MacWarrior** [comment]
No problem, will fix it soon ;)

**Comment by MacWarrior** [comment]
Hi,

Please update to latest revision :)

**Comment by spirogg** [comment]
ok any way to change this to use m-d-Y instead of Y-m-d ?

**Comment by spirogg** [comment]
OK I see now I have it working changed in configuration m-d-Y

- anyway to get the drop down on calendar to scroll more years ? we have to select the last loaded year then re-select to scroll lower down the years ? 
![scroll calendar](https://user-images.githubusercontent.com/17736688/40589384-dab29fee-61b1-11e8-8c34-f098e40035b1.PNG)
![scroll again](https://user-images.githubusercontent.com/17736688/40589385-dd131b9c-61b1-11e8-8651-5208f33c2e15.PNG)
![scroll again1](https://user-images.githubusercontent.com/17736688/40589387-dfb5ac98-61b1-11e8-9b68-89579bc21272.PNG)

**Comment by spirogg** [comment]
2) also when you use calendar to select your date of birth, 
after when your done it first shows Y-m-d but after you save it,  its correct ?

is there a way to fix this also in calendar ?


![selector](https://user-images.githubusercontent.com/17736688/40589437-de7c2734-61b2-11e8-9501-05e46784eb56.PNG)
![selector y m d](https://user-images.githubusercontent.com/17736688/40589439-e2e2bc84-61b2-11e8-845f-9868a0e229e0.PNG)
![selector ok](https://user-images.githubusercontent.com/17736688/40589440-e4dca70c-61b2-11e8-8821-5473728c9b48.PNG)

**Comment by spirogg** [comment]
Also I see if we try to input d-m-Y by numerical numbers example 12-14-1980 and click save button  won't save. In chrome browser I tested this only.

**Comment by MacWarrior** [comment]
Hi, 
Fixed in this commit : c34742af4858132afd6a5f1ed0710c5f61b9dd4d
