### ISSUE TITLE
When view profile of user :info >more I see category 3 times listed ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#94]
Hi when you view a profile you see what category they are in I am in basic. 
When I click more. To view more info, It shows category 3 times..

**Comment by spirogg** [comment]
![screenshot_20190104-154116](https://user-images.githubusercontent.com/17736688/50712651-e273db00-1037-11e9-8359-2f5e04361898.png)

**Comment by spirogg** [comment]
![screenshot_20190104-154124](https://user-images.githubusercontent.com/17736688/50712712-118a4c80-1038-11e9-903c-0528c72db06b.png)

**Comment by spirogg** [comment]
![screenshot_20190104-153440](https://user-images.githubusercontent.com/17736688/50713145-8ad66f00-1039-11e9-975b-7fd1aff3c274.png)

**Comment by spirogg** [comment]
same on original CB demo site

User activity
Title:my videos
Description:cool videos
Joined: 3 months ago
Last Login:1 minute ago
User Status:  online
Basic info
Relationship Status: Married
**Category: Guru**
Location
Country:  Canada
**Category: Guru**
Education, Hobbies, etc
Education: Master’s Degree
**Category: Guru**

**Comment by MacWarrior** [comment]
Hi,
Fixed in last commit
