### ISSUE TITLE
Email sent with new password (if forgot password) link to site to login is not working 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#95]
Hi when you forgot password, you get one email and click on reset password works,. Then it sends you another email with a password. There is a link that says click here to login 

That sends you to invalid url: http:///login.php not tye website login form.  Just FYI.

**Comment by MacWarrior** [comment]
Hi,
As I already said, all emails (and all emailing system) must be refactored (very badly done...)
But URLs are not fixed :smile:
